export const ADD_NOTE = 'ADD_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';

export const PLAY_TRACK = 'PLAY_TRACK';
export const STOP_TRACK = 'STOP_TRACK';

export const MUTE_MASTER = 'MUTE_MASTER';
export const UNMUTE_MASTER = 'UNMUTE_MASTER';

export const SET_MASTER_VOLUME = 'SET_MASTER_VOLUME'; 

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const REMOVE_CHANNEL = 'REMOVE_CHANNEL';

export const ADD_SECTION = 'ADD_SECTION';
export const REMOVE_SECTION = 'REMOVE_SECTION';

export const ADD_INSTRUMENT = 'ADD_INSTRUMENT';
export const REMOVE_INSTRUMENT = 'REMOVE_INSTRUMENT';

export const ADD_EFFECT = 'ADD_EFFECT';
export const REMOVE_EFFECT = 'REMOVE_EFFECT';

export const UPDATE_INSTRUMENT_SETTINGS = 'UPDATE_INSTRUMENT_SETTINGS';
export const UPDATE_EFFECT_SETTINGS = 'UPDATE_EFFECT_SETTINGS';

export const OPEN_WINDOW = 'OPEN_WINDOW';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';