export const ADD_NOTE = 'ADD_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';
export const ADD_EVENT_TO_QUEUE = 'ADD_EVENT_TO_QUEUE';
export const REMOVE_EVENT_FROM_QUEUE = 'REMOVE_EVENT_FROM_QUEUE';
export const PLAY_TRACK = 'PLAY_TRACK';
export const STOP_TRACK = 'STOP_TRACK';