export const SAVE_STATE_ATTEMPT = 'SAVE_STATE';
export const SAVE_STATE_SUCCESS = 'SAVE_STATE_SUCCESS';
export const SAVE_STATE_FAILED = 'SAVE_STATE_FAILED';
export const LOAD_STATE_ATTEMPT = 'LOAD_STATE';
export const LOAD_STATE_SUCCESS = 'LOAD_STATE_SUCCESS';
export const LOAD_STATE_FAILED = 'LOAD_STATE_FAILED';
